name: Math Utility Repo applying CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Distribute jar-war file
      run: |
        mkdir staging
        cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      

    - name: Make hyperlink to jar-war file
      uses: actions/upload-artifact@v1
      with:
        name: HÃY-CLICK-EM-ĐỂ-LẤY-FILE-JAR-VỀ-NHÀ-LOCAL
        path: staging
